name: pull-request-test
on:
  workflow_dispatch:
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ワークフローの可視化
      - uses: Kesin11/actions-timeline@v2
      # チェックアウト
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      # GCRにログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/tomo1227/template_devcontainer-devcontainer
